'use strict';

exports.seed = function(knex, Promise) {

  return knex('cities').del()
  .then(function() {
    return Promise.all([
      knex('cities').insert({"city": "Denver","country": "United States"}),
      knex('cities').insert({"city": "Madrid", "country": "Spain"}),
      knex('cities').insert({"city": "Seville", "country": "Spain"}),
      knex('cities').insert({"city": "Seattle", "country": "United States"}),
      knex('cities').insert({"city": "London", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Paris", "country": "France"}),
      knex('cities').insert({ "city": "Sacramento", "country": "United States"}),
      knex('cities').insert({ "city": "Honolulu", "country": "United States"}),
      knex('cities').insert({"city": "Los Angeles","country": "United States"}),
      knex('cities').insert({ "city": "Fairbanks","country": "United States"}),
      knex('cities').insert({"city": "Juneau", "country": "United States"}),
      knex('cities').insert({"city": "Vancouver","country": "Canada"}),
      knex('cities').insert({"city": "San Francisco","country": "United States"}),
      knex('cities').insert({"city": "San Diego","country": "United States"}),
      knex('cities').insert({"city": "Tijuana", "country": "Mexico"}),
      knex('cities').insert({"city": "Mexicali","country": "Mexico"}),
      knex('cities').insert({"city": "Las Vegas","country": "United States"}),
      knex('cities').insert({"city": "Calgary", "country": "Canada"}),
      knex('cities').insert({"city": "Phoenix", "country": "United States"}),
      knex('cities').insert({"city": "Salt Lake City","country": "United States"}),
      knex('cities').insert({"city": "Tucson", "country": "United States"}),
      knex('cities').insert({"city": "Hanga Roa", "country": "Chile"}),
      knex('cities').insert({"city": "Saskatoon", "country": "Canada"}),
      knex('cities').insert({"city": "Albuquerque", "country": "United States"}),
      knex('cities').insert({"city": "El Paso","country": "United States"}),
      knex('cities').insert({"city": "Chihuahua", "country": "Mexico"}),
      knex('cities').insert({"city": "Durango", "country": "Mexico"}),
      knex('cities').insert({"city": "Guadalajara", "country": "Mexico"}),
      knex('cities').insert({"city": "Monterrey", "country": "Mexico"}),
      knex('cities').insert({"city": "Mexico City", "country": "Mexico"}),
      knex('cities').insert({"city": "San Antonio","country": "United States"}),
      knex('cities').insert({"city": "Puebla", "country": "Mexico"}),
      knex('cities').insert({"city": "Austin", "country": "United States"}),
      knex('cities').insert({"city": "Oklahoma City", "country": "United States"}),
      knex('cities').insert({"city": "Wichita", "country": "United States"}),
      knex('cities').insert({"city": "Winnipeg", "country": "Canada"}),
      knex('cities').insert({"city": "Dallas", "country": "United States"}),
      knex('cities').insert({"city": "Veracruz", "country": "Mexico"}),
      knex('cities').insert({"city": "Houston", "country": "United States"}),
      knex('cities').insert({"city": "Kansas City", "country": "United States"}),
      knex('cities').insert({"city": "Minneapolis", "country": "United States"}),
      knex('cities').insert({"city": "Quetzaltenango", "country": "Guatemala"}),
      knex('cities').insert({"city": "Guatemala City", "country": "Guatemala"}),
      knex('cities').insert({"city": "New Orleans", "country": "United States"}),
      knex('cities').insert({"city": "Memphis", "country": "United States"}),
      knex('cities').insert({"city": "Mérida", "country": "Mexico"}),
      knex('cities').insert({"city": "San Salvador", "country": "El Salvador"}),
      knex('cities').insert({"city": "Belize City", "country": "Belize"}),
      knex('cities').insert({"city": "Milwaukee", "country": "United States"}),
      knex('cities').insert({"city": "Chicago", "country": "United States"}),
      knex('cities').insert({"city": "Tegucigalpa", "country": "Honduras"}),
      knex('cities').insert({"city": "Nashville", "country": "United States"}),
      knex('cities').insert({"city": "Managua", "country": "Nicaragua"}),
      knex('cities').insert({"city": "Indianapolis", "country": "United States"}),
      knex('cities').insert({"city": "Louisville", "country": "United States"}),
      knex('cities').insert({"city": "Cincinnati", "country": "United States"}),
      knex('cities').insert({"city": "Atlanta", "country": "United States"}),
      knex('cities').insert({"city": "San José", "country": "Costa Rica"}),
      knex('cities').insert({"city": "Detroit", "country": "United States"}),
      knex('cities').insert({"city": "Columbus", "country": "United States"}),
      knex('cities').insert({"city": "Tampa", "country": "United States"}),
      knex('cities').insert({"city": "Havana", "country": "Cuba"}),
      knex('cities').insert({"city": "Cleveland", "country": "United States"}),
      knex('cities').insert({"city": "Jacksonville", "country": "United States"}),
      knex('cities').insert({"city": "Charlotte", "country": "United States"}),
      knex('cities').insert({"city": "Miami", "country": "United States"}),
      knex('cities').insert({"city": "Pittsburgh", "country": "United States"}),
      knex('cities').insert({"city": "Guayaquil", "country": "Ecuador"}),
      knex('cities').insert({"city": "Panama City", "country": "Panama"}),
      knex('cities').insert({"city": "Toronto", "country": "Canada"}),
      knex('cities').insert({"city": "Buffalo", "country": "United States"}),
      knex('cities').insert({"city": "Raleigh", "country": "United States"}),
      knex('cities').insert({"city": "Quito", "country": "Ecuador"}),
      knex('cities').insert({"city": "Rochester", "country": "United States"}),
      knex('cities').insert({"city": "Nassau", "country": "The Bahamas"}),
      knex('cities').insert({"city": "Washington", "country": "United States"}),
      knex('cities').insert({"city": "Lima", "country": "Peru"}),
      knex('cities').insert({"city": "Kingston", "country": "Jamaica"}),
      knex('cities').insert({"city": "Baltimore", "country": "United States"}),
      knex('cities').insert({"city": "Cali", "country": "Colombia"}),
      knex('cities').insert({"city": "Virginia Beach", "country": "United States"}),
      knex('cities').insert({"city": "Ottawa", "country": "Canada"}),
      knex('cities').insert({"city": "Medellín", "country": "Colombia"}),
      knex('cities').insert({"city": "Cartagena", "country": "Colombia"}),
      knex('cities').insert({"city": "Philadelphia", "country": "United States"}),
      knex('cities').insert({"city": "Barranquilla", "country": "Colombia"}),
      knex('cities').insert({"city": "Fort Collins", "country": "United States"}),
      knex('cities').insert({"city": "Jersey City", "country": "United States"}),
      knex('cities').insert({"city": "Bogotá", "country": "Colombia"}),
      knex('cities').insert({"city": "Montreal", "country": "Canada"}),
      knex('cities').insert({"city": "Iquitos", "country": "Peru"}),
      knex('cities').insert({"city": "Valdivia", "country": "Chile"}),
      knex('cities').insert({"city": "Concepción", "country": "Chile"}),
      knex('cities').insert({"city": "Cusco", "country": "Peru"}),
      knex('cities').insert({"city": "Maracaibo", "country": "Venezuela"}),
      knex('cities').insert({"city": "Valparaíso", "country": "Chile"}),
      knex('cities').insert({"city": "Arequipa", "country": "Peru"}),
      knex('cities').insert({"city": "Providence", "country": "United States"}),
      knex('cities').insert({"city": "La Serena", "country": "Chile"}),
      knex('cities').insert({"city": "Cockburn Town", "country": "Turks and Caicos Islands"}),
      knex('cities').insert({"city": "Boston", "country": "United States"}),
      knex('cities').insert({"city": "Punta Arenas", "country": "Chile"}),
      knex('cities').insert({"city": "Santiago", "country": "Chile"}),
      knex('cities').insert({"city": "Antofagasta", "country": "Chile"}),
      knex('cities').insert({"city": "Iquique", "country": "Chile"}),
      knex('cities').insert({"city": "Oranjestad", "country": "Aruba"}),
      knex('cities').insert({"city": "Santo Domingo", "country": "Dominican Republic"}),
      knex('cities').insert({"city": "Rio Branco", "country": "Brazil"}),
      knex('cities').insert({"city": "Mendoza", "country": "Argentina"}),
      knex('cities').insert({"city": "Ushuaia", "country": "Argentina"}),
      knex('cities').insert({"city": "La Paz", "country": "Bolivia"}),
      knex('cities').insert({"city": "Caracas", "country": "Venezuela"}),
      knex('cities').insert({"city": "San Juan", "country": "Puerto Rico"}),
      knex('cities').insert({"city": "Sucre", "country": "Bolivia"}),
      knex('cities').insert({"city": "Córdoba", "country": "Argentina"}),
      knex('cities').insert({"city": "Porto Velho", "country": "Brazil"}),
      knex('cities').insert({"city": "Buenos Aires", "country": "Argentina"}),
      knex('cities').insert({"city": "Stanley", "country": "Hong Kong"}),
      knex('cities').insert({"city": "Asunción", "country": "Paraguay"}),
      knex('cities').insert({"city": "Montevideo", "country": "Uruguay"}),
      knex('cities').insert({"city": "Paramaribo", "country": "Suriname"}),
      knex('cities').insert({"city": "Porto Alegre", "country": "Brazil"}),
      knex('cities').insert({"city": "Macapá", "country": "Brazil"}),
      knex('cities').insert({"city": "Brasília", "country": "Brazil"}),
      knex('cities').insert({"city": "São Paulo", "country": "Brazil"}),
      knex('cities').insert({"city": "Fortaleza", "country": "Brazil"}),
      knex('cities').insert({"city": "Recife", "country": "Brazil"}),
      knex('cities').insert({"city": "Praia", "country": "Brazil"}),
      knex('cities').insert({"city": "Reykjavík", "country": "Iceland"}),
      knex('cities').insert({"city": "Dakar", "country": "Senegal"}),
      knex('cities').insert({"city": "Lisbon", "country": "Portugal"}),
      knex('cities').insert({"city": "Porto", "country": "Brazil"}),
      knex('cities').insert({"city": "Casablanca", "country": "Morocco"}),
      knex('cities').insert({"city": "Rabat", "country": "Morocco"}),
      knex('cities').insert({"city": "Dublin", "country": "Ireland"}),
      knex('cities').insert({"city": "Belfast", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Jamestown", "country": "United States"}),
      knex('cities').insert({"city": "Gibraltar", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Málaga", "country": "Spain"}),
      knex('cities').insert({"city": "Glasgow", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Cardiff", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Edinburgh", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Liverpool", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Bilbao", "country": "Spain"}),
      knex('cities').insert({"city": "Manchester", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Aberdeen", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Birmingham", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Leeds", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Valencia", "country": "Spain"}),
      knex('cities').insert({"city": "Accra", "country": "Ghana"}),
      knex('cities').insert({"city": "Greenwich", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Toulouse", "country": "France"}),
      knex('cities').insert({"city": "Ibiza", "country": "Spain"}),
      knex('cities').insert({"city": "Barcelona", "country": "Spain"}),
      knex('cities').insert({"city": "Palma de Mallorca", "country": "Spain"}),
      knex('cities').insert({"city": "Algiers", "country": "Algeria"}),
      knex('cities').insert({"city": "The Hague", "country": "Netherlands"}),
      knex('cities').insert({"city": "Brussels", "country": "Belgium"}),
      knex('cities').insert({"city": "Antwerp", "country": "Belgium"}),
      knex('cities').insert({"city": "Rotterdam", "country": "Netherlands"}),
      knex('cities').insert({"city": "Lyon", "country": "France"}),
      knex('cities').insert({"city": "Amsterdam", "country": "Netherlands"}),
      knex('cities').insert({"city": "Marseille", "country": "France"}),
      knex('cities').insert({"city": "Geneva", "country": "Switzerland"}),
      knex('cities').insert({"city": "São Tomé", "country": "Brazil"}),
      knex('cities').insert({"city": "Düsseldorf", "country": "Germany"}),
      knex('cities').insert({"city": "Cologne", "country": "Germany"}),
      knex('cities').insert({"city": "Cannes", "country": "France"}),
      knex('cities').insert({"city": "Nice", "country": "France"}),
      knex('cities').insert({"city": "Monaco", "country": "Monaco"}),
      knex('cities').insert({"city": "Turin", "country": "Italy"}),
      knex('cities').insert({"city": "Strasbourg", "country": "France"}),
      knex('cities').insert({"city": "Zürich", "country": "Switzerland"}),
      knex('cities').insert({"city": "Frankfurt", "country": "Germany"}),
      knex('cities').insert({"city": "Malabo", "country": "Philippines"}),
      knex('cities').insert({"city": "Stuttgart", "country": "Germany"}),
      knex('cities').insert({"city": "Milan", "country": "Italy"}),
      knex('cities').insert({"city": "Vaduz", "country": "Liechtenstein"}),
      knex('cities').insert({"city": "Hanover", "country": "Germany"}),
      knex('cities').insert({"city": "Hamburg", "country": "Germany"}),
      knex('cities').insert({"city": "Tunis", "country": "Tunisia"}),
      knex('cities').insert({"city": "Oslo", "country": "Norway"}),
      knex('cities').insert({"city": "Munich", "country": "Germany"}),
      knex('cities').insert({"city": "Rome", "country": "Italy"}),
      knex('cities').insert({"city": "Copenhagen", "country": "Denmark"}),
      knex('cities').insert({"city": "Berlin", "country": "Germany"}),
      knex('cities').insert({"city": "Naples", "country": "Italy"}),
      knex('cities').insert({"city": "Prague", "country": "Czech Republic"}),
      knex('cities').insert({"city": "Valletta", "country": "Malta"}),
      knex('cities').insert({"city": "Zagreb", "country": "Croatia"}),
      knex('cities').insert({"city": "Vienna", "country": "Austria"}),
      knex('cities').insert({"city": "Stockholm", "country": "Sweden"}),
      knex('cities').insert({"city": "Sarajevo", "country": "Bosnia and Herzegovina"}),
      knex('cities').insert({"city": "Cape Town", "country": "South Africa"}),
      knex('cities').insert({"city": "Budapest", "country": "Hungary"}),
      knex('cities').insert({"city": "Kraków", "country": "Poland"}),
      knex('cities').insert({"city": "Warsaw", "country": "Poland"}),
      knex('cities').insert({"city": "Athens", "country": "Greece"}),
      knex('cities').insert({"city": "Helsinki", "country": "Finland"}),
      knex('cities').insert({"city": "Johannesburg", "country": "South Africa"}),
      knex('cities').insert({"city": "Pretoria", "country": "South Africa"}),
      knex('cities').insert({"city": "Istanbul", "country": "Turkey"}),
      knex('cities').insert({"city": "Saint Petersburg", "country": "Russia"}),
      knex('cities').insert({"city": "Cairo", "country": "Egypt"}),
      knex('cities').insert({"city": "Ankara", "country": "Turkey"}),
      knex('cities').insert({"city": "Gaza", "country": "Palestine"}),
      knex('cities').insert({"city": "Tel Aviv", "country": "Israel"}),
      knex('cities').insert({"city": "Jerusalem", "country": "Israel"}),
      knex('cities').insert({"city": "Amman", "country": "Jordan"}),
      knex('cities').insert({"city": "Damascus", "country": "Syria"}),
      knex('cities').insert({"city": "Moscow", "country": "Russia"}),
      knex('cities').insert({"city": "Dubai", "country": "United Arab Emirates"}),
      knex('cities').insert({"city": "Bangkok", "country": "Thailand"}),
      knex('cities').insert({"city": "Pattaya", "country": "Thailand"}),
      knex('cities').insert({"city": "Singapore", "country": "Singapore"}),
      knex('cities').insert({"city": "Phnom Penh", "country": "Cambodia"}),
      knex('cities').insert({"city": "Hanoi", "country": "Vietnam"}),
      knex('cities').insert({"city": "Ho Chi Minh City", "country": "Vietnam"}),
      knex('cities').insert({"city": "Guangzhou", "country": "China"}),
      knex('cities').insert({"city": "Macau", "country": "Macau"}),
      knex('cities').insert({"city": "Hong Kong", "country": "Hong Kong"}),
      knex('cities').insert({"city": "Perth", "country": "Australia"}),
      knex('cities').insert({"city": "Beijing", "country": "China"}),
      knex('cities').insert({"city": "Shanghai", "country": "China"}),
      knex('cities').insert({"city": "Seoul", "country": "South Korea"}),
      knex('cities').insert({"city": "Osaka", "country": "Japan"}),
      knex('cities').insert({"city": "Kyoto", "country": "Japan"}),
      knex('cities').insert({"city": "Nagoya", "country": "Japan"}),
      knex('cities').insert({"city": "Melbourne", "country": "Australia"}),
      knex('cities').insert({"city": "Canberra", "country": "Australia"}),
      knex('cities').insert({"city": "Newcastle", "country": "United Kingdom"}),
      knex('cities').insert({"city": "Brisbane", "country": "Australia"}),
      knex('cities').insert({"city": "Auckland", "country": "New Zealand"}),
      knex('cities').insert({"city": "St. Louis", "country": "United States"}),
      knex('cities').insert({"city": "Santiago de Cuba", "country": "Cuba"}),
      knex('cities').insert({"city": "New York City", "country": "United States"}),
      knex('cities').insert({"city": "Port-au-Prince", "country": "Haiti"}),
      knex('cities').insert({"city": "Quebec City", "country": "Canada"}),
      knex('cities').insert({"city": "City of Halifax", "country": "Canada"}),
      knex('cities').insert({"city": "Port of Spain", "country": "Trinidad and Tobago"}),
      knex('cities').insert({"city": "Fort-de-France", "country": "Martinique"}),
      knex('cities').insert({"city": "Rio de Janeiro", "country": "Brazil"}),
      knex('cities').insert({"city": "Santa Cruz de Tenerife", "country": "Spain"}),
      knex('cities').insert({"city": "Las Palmas de Gran Canaria", "country": "Spain"}),
      knex('cities').insert({"city": "Cork (city)", "country": "Ireland"}),
      knex('cities').insert({"city": "Marrakech", "country": "Morocco"}),
      knex('cities').insert({"city": "Huế", "country": "Vietnam"}),
      knex('cities').insert({"city": "Xi'an", "country": "China"}),
      knex('cities').insert({"city": "Tokyo", "country": "Japan"})
    ]);
  });

};
