'use strict';

exports.seed = function(knex, Promise) {

  return knex('cities_es').del()
  .then(function() {
    return Promise.all([
      knex('cities_es').insert({"city": "Denver","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Madrid", "country": "España"}),
      knex('cities_es').insert({"city": "Sevilla", "country": "España"}),
      knex('cities_es').insert({"city": "Seattle", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Londres", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "París", "country": "Francia"}),
      knex('cities_es').insert({"city": "Sacramento", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Honolulu", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Los Angeles","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Fairbanks","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Juneau", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Vancouver","country": "Canadá"}),
      knex('cities_es').insert({"city": "San Francisco","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "San Diego","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Tijuana", "country": "México"}),
      knex('cities_es').insert({"city": "Mexicali","country": "México"}),
      knex('cities_es').insert({"city": "Las Vegas","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Calgary", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Phoenix", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Salt Lake City","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Tucson", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Hanga Roa", "country": "Chile"}),
      knex('cities_es').insert({"city": "Saskatoon", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Albuquerque", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "El Paso","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Chihuahua", "country": "México"}),
      knex('cities_es').insert({"city": "Durango", "country": "México"}),
      knex('cities_es').insert({"city": "Guadalajara", "country": "México"}),
      knex('cities_es').insert({"city": "Monterrey", "country": "México"}),
      knex('cities_es').insert({"city": "México DF", "country": "México"}),
      knex('cities_es').insert({"city": "San Antonio","country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Puebla", "country": "México"}),
      knex('cities_es').insert({"city": "Austin", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Oklahoma City", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Wichita", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Winnipeg", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Dallas", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Veracruz", "country": "México"}),
      knex('cities_es').insert({"city": "Houston", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Kansas City", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Minneapolis", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Quetzaltenango", "country": "Guatemala"}),
      knex('cities_es').insert({"city": "Ciudad de Guatemala", "country": "Guatemala"}),
      knex('cities_es').insert({"city": "New Orleans", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Memphis", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Mérida", "country": "México"}),
      knex('cities_es').insert({"city": "San Salvador", "country": "El Salvador"}),
      knex('cities_es').insert({"city": "Ciudad de Belice", "country": "Belice"}),
      knex('cities_es').insert({"city": "Milwaukee", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Chicago", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Tegucigalpa", "country": "Honduras"}),
      knex('cities_es').insert({"city": "Nashville", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Managua", "country": "Nicaragua"}),
      knex('cities_es').insert({"city": "Indianapolis", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Louisville", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Cincinnati", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Atlanta", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "San José", "country": "Costa Rica"}),
      knex('cities_es').insert({"city": "Detroit", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Columbus", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Tampa", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "La Habana", "country": "Cuba"}),
      knex('cities_es').insert({"city": "Cleveland", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Jacksonville", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Charlotte", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Miami", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Pittsburgh", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Guayaquil", "country": "Ecuador"}),
      knex('cities_es').insert({"city": "Ciudad de Panamá", "country": "Panamá"}),
      knex('cities_es').insert({"city": "Toronto", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Buffalo", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Raleigh", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Quito", "country": "Ecuador"}),
      knex('cities_es').insert({"city": "Rochester", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Nassau", "country": "Las Bahamas"}),
      knex('cities_es').insert({"city": "Washington DC", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Lima", "country": "Peru"}),
      knex('cities_es').insert({"city": "Kingston", "country": "Jamaica"}),
      knex('cities_es').insert({"city": "Baltimore", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Cali", "country": "Colombia"}),
      knex('cities_es').insert({"city": "Virginia Beach", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Ottawa", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Medellín", "country": "Colombia"}),
      knex('cities_es').insert({"city": "Cartagena", "country": "Colombia"}),
      knex('cities_es').insert({"city": "Philadelphia", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Barranquilla", "country": "Colombia"}),
      knex('cities_es').insert({"city": "Fort Collins", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Jersey City", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Bogotá", "country": "Colombia"}),
      knex('cities_es').insert({"city": "Montreal", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Cusco", "country": "Peru"}),
      knex('cities_es').insert({"city": "Maracaibo", "country": "Venezuela"}),
      knex('cities_es').insert({"city": "Valparaíso", "country": "Chile"}),
      knex('cities_es').insert({"city": "Arequipa", "country": "Peru"}),
      knex('cities_es').insert({"city": "Providence", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "La Serena", "country": "Chile"}),
      knex('cities_es').insert({"city": "Boston", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Punta Arenas", "country": "Chile"}),
      knex('cities_es').insert({"city": "Santiago", "country": "Chile"}),
      knex('cities_es').insert({"city": "Santo Domingo", "country": "La República Dominicana"}),
      knex('cities_es').insert({"city": "Rio Branco", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Mendoza", "country": "Argentina"}),
      knex('cities_es').insert({"city": "Ushuaia", "country": "Argentina"}),
      knex('cities_es').insert({"city": "La Paz", "country": "Bolivia"}),
      knex('cities_es').insert({"city": "Caracas", "country": "Venezuela"}),
      knex('cities_es').insert({"city": "San Juan", "country": "Puerto Rico"}),
      knex('cities_es').insert({"city": "Sucre", "country": "Bolivia"}),
      knex('cities_es').insert({"city": "Córdoba", "country": "Argentina"}),
      knex('cities_es').insert({"city": "Porto Velho", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Buenos Aires", "country": "Argentina"}),
      knex('cities_es').insert({"city": "Stanley", "country": "Hong Kong"}),
      knex('cities_es').insert({"city": "Asunción", "country": "Paraguay"}),
      knex('cities_es').insert({"city": "Montevideo", "country": "Uruguay"}),
      knex('cities_es').insert({"city": "Paramaribo", "country": "Suriname"}),
      knex('cities_es').insert({"city": "Porto Alegre", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Macapá", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Brasília", "country": "Brasil"}),
      knex('cities_es').insert({"city": "São Paulo", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Fortaleza", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Recife", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Praia", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Reykjavík", "country": "Iceland"}),
      knex('cities_es').insert({"city": "Dakar", "country": "Senegal"}),
      knex('cities_es').insert({"city": "Lisboa", "country": "Portugal"}),
      knex('cities_es').insert({"city": "Porto", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Casablanca", "country": "Marruecos"}),
      knex('cities_es').insert({"city": "Rabat", "country": "Marruecos"}),
      knex('cities_es').insert({"city": "Dublín", "country": "Irlanda"}),
      knex('cities_es').insert({"city": "Belfast", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Jamestown", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Gibraltar", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Málaga", "country": "España"}),
      knex('cities_es').insert({"city": "Glasgow", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Cardiff", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Edinburgh", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Liverpool", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Bilbao", "country": "España"}),
      knex('cities_es').insert({"city": "Manchester", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Aberdeen", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Birmingham", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Leeds", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Valencia", "country": "España"}),
      knex('cities_es').insert({"city": "Greenwich", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Toulouse", "country": "Francia"}),
      knex('cities_es').insert({"city": "Ibiza", "country": "España"}),
      knex('cities_es').insert({"city": "Barcelona", "country": "España"}),
      knex('cities_es').insert({"city": "Palma de Mallorca", "country": "España"}),
      knex('cities_es').insert({"city": "Algiers", "country": "Algeria"}),
      knex('cities_es').insert({"city": "La Haya", "country": "Países Bajos"}),
      knex('cities_es').insert({"city": "Bruselas", "country": "Bélgica"}),
      knex('cities_es').insert({"city": "Antwerp", "country": "Bélgica"}),
      knex('cities_es').insert({"city": "Rotterdam", "country": "Países Bajos"}),
      knex('cities_es').insert({"city": "Lyon", "country": "Francia"}),
      knex('cities_es').insert({"city": "Ámsterdam", "country": "Países Bajos"}),
      knex('cities_es').insert({"city": "Marseille", "country": "Francia"}),
      knex('cities_es').insert({"city": "Ginebra", "country": "Suiza"}),
      knex('cities_es').insert({"city": "São Tomé", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Düsseldorf", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Cologne", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Cannes", "country": "Francia"}),
      knex('cities_es').insert({"city": "Nice", "country": "Francia"}),
      knex('cities_es').insert({"city": "Monaco", "country": "Monaco"}),
      knex('cities_es').insert({"city": "Turín", "country": "Italia"}),
      knex('cities_es').insert({"city": "Strasbourg", "country": "Francia"}),
      knex('cities_es').insert({"city": "Zürich", "country": "Suiza"}),
      knex('cities_es').insert({"city": "Frankfurt", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Malabo", "country": "Filipinas"}),
      knex('cities_es').insert({"city": "Stuttgart", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Milán", "country": "Italia"}),
      knex('cities_es').insert({"city": "Hanover", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Hamburgo", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Túnez", "country": "Túnez"}),
      knex('cities_es').insert({"city": "Oslo", "country": "Noruega"}),
      knex('cities_es').insert({"city": "Múnich", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Roma", "country": "Italia"}),
      knex('cities_es').insert({"city": "Copenhagen", "country": "Denmark"}),
      knex('cities_es').insert({"city": "Berlín", "country": "Alemania"}),
      knex('cities_es').insert({"city": "Napoles", "country": "Italia"}),
      knex('cities_es').insert({"city": "Praga", "country": "República Checa"}),
      knex('cities_es').insert({"city": "Valletta", "country": "Malta"}),
      knex('cities_es').insert({"city": "Zagreb", "country": "Croacia"}),
      knex('cities_es').insert({"city": "Vienna", "country": "Austria"}),
      knex('cities_es').insert({"city": "Estocolmo", "country": "Suecia"}),
      knex('cities_es').insert({"city": "Sarajevo", "country": "Bosnia y Herzegovina"}),
      knex('cities_es').insert({"city": "Ciudad de Cabo", "country": "Sudáfrica"}),
      knex('cities_es').insert({"city": "Budapest", "country": "Hungría"}),
      knex('cities_es').insert({"city": "Kraków", "country": "Polonia"}),
      knex('cities_es').insert({"city": "Warsaw", "country": "Polonia"}),
      knex('cities_es').insert({"city": "Atenas", "country": "Grecia"}),
      knex('cities_es').insert({"city": "Helsinki", "country": "Finlandia"}),
      knex('cities_es').insert({"city": "Johannesburg", "country": "Sudáfrica"}),
      knex('cities_es').insert({"city": "Pretoria", "country": "Sudáfrica"}),
      knex('cities_es').insert({"city": "Estambul", "country": "Turquía"}),
      knex('cities_es').insert({"city": "San Petersburgo", "country": "Rusia"}),
      knex('cities_es').insert({"city": "Cairo", "country": "Egipto"}),
      knex('cities_es').insert({"city": "Ankara", "country": "Turquía"}),
      knex('cities_es').insert({"city": "Gaza", "country": "Palestina"}),
      knex('cities_es').insert({"city": "Tel Aviv", "country": "Israel"}),
      knex('cities_es').insert({"city": "Jerusalén", "country": "Israel"}),
      knex('cities_es').insert({"city": "Amman", "country": "Jordania"}),
      knex('cities_es').insert({"city": "Damasco", "country": "Siria"}),
      knex('cities_es').insert({"city": "Moscú", "country": "Rusia"}),
      knex('cities_es').insert({"city": "Dubai", "country": "Emiratos Árabes Unidos"}),
      knex('cities_es').insert({"city": "Bangkok", "country": "Tailandia"}),
      knex('cities_es').insert({"city": "Pattaya", "country": "Tailandia"}),
      knex('cities_es').insert({"city": "Singapur", "country": "Singapur"}),
      knex('cities_es').insert({"city": "Phnom Penh", "country": "Cambodia"}),
      knex('cities_es').insert({"city": "Hanoi", "country": "Vietnam"}),
      knex('cities_es').insert({"city": "Ciudad de Ho Chi Minh", "country": "Vietnam"}),
      knex('cities_es').insert({"city": "Guangzhou", "country": "China"}),
      knex('cities_es').insert({"city": "Macao", "country": "Macao"}),
      knex('cities_es').insert({"city": "Hong Kong", "country": "China"}),
      knex('cities_es').insert({"city": "Perth", "country": "Australia"}),
      knex('cities_es').insert({"city": "Beijing", "country": "China"}),
      knex('cities_es').insert({"city": "Shanghai", "country": "China"}),
      knex('cities_es').insert({"city": "Seúl", "country": "Corea del Sur"}),
      knex('cities_es').insert({"city": "Osaka", "country": "Japón"}),
      knex('cities_es').insert({"city": "Kioto", "country": "Japón"}),
      knex('cities_es').insert({"city": "Melbourne", "country": "Australia"}),
      knex('cities_es').insert({"city": "Canberra", "country": "Australia"}),
      knex('cities_es').insert({"city": "Newcastle", "country": "Reino Unido"}),
      knex('cities_es').insert({"city": "Brisbane", "country": "Australia"}),
      knex('cities_es').insert({"city": "Auckland", "country": "Nueva Zelanda"}),
      knex('cities_es').insert({"city": "St. Louis", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Santiago de Cuba", "country": "Cuba"}),
      knex('cities_es').insert({"city": "New York City", "country": "Estados Unidos"}),
      knex('cities_es').insert({"city": "Port-au-Prince", "country": "Haití"}),
      knex('cities_es').insert({"city": "Quebec City", "country": "Canadá"}),
      knex('cities_es').insert({"city": "City of Halifax", "country": "Canadá"}),
      knex('cities_es').insert({"city": "Port of España", "country": "Trinidad y Tobago"}),
      knex('cities_es').insert({"city": "Fort-de-Francia", "country": "Martinique"}),
      knex('cities_es').insert({"city": "Rio de Janeiro", "country": "Brasil"}),
      knex('cities_es').insert({"city": "Santa Cruz de Tenerife", "country": "España"}),
      knex('cities_es').insert({"city": "Las Palmas de Gran Canaria", "country": "España"}),
      knex('cities_es').insert({"city": "Cork", "country": "Irlanda"}),
      knex('cities_es').insert({"city": "Marrakech", "country": "Marruecos"}),
      knex('cities_es').insert({"city": "Huế", "country": "Vietnam"}),
      knex('cities_es').insert({"city": "Xi'an", "country": "China"}),
      knex('cities_es').insert({"city": "Tokio", "country": "Japón"})
    ]);
  });

};
