'use strict';

exports.seed = function(knex, Promise) {
  //deletes all existing entries
  return knex('users').del()
    .then(function() {
      return Promise.all([
        knex.raw('ALTER SEQUENCE public.users_id_seq RESTART WITH 37;'),
        knex('users').insert({"id": 1,"name":"Jessica","email":"demo@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Hi, guys! I'm looking for an exchange partner to practice Spanish with twice a week.","age":23,"photo_url":"http://ww3.madonna.edu/crusaders/Images/story/WSOCC/austin_sign.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id": 2,"name":"Bonnie","email":"bclyde@gmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I like speaking Spanish in my free time. Let's meet up for a coffee or beer.","age":62,"photo_url":"http://vignette1.wikia.nocookie.net/stargate/images/4/44/BB.jpg/revision/latest?cb=20150331174051","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id": 3,"name":"Lorena","email":"ppeters2@mediafire.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I need to practice my English. I would love to meet in person or online!","age":25,"photo_url":"http://www.ggcalumni.net/image/four-pillar-society/2015-headshots/lorena/Lorena.jpg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id": 4,"name":"David","email":"blopez3@youtu.be","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Need some basic conversational skills and can meet anytime on the weekends. Message me if you want to get in touch.","age":20,"photo_url":"https://pbs.twimg.com/profile_images/646374589916778496/i53D1Q35.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id": 5,"name":"Alexa","email":"acasas@yahoo.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I'm a foreign exchange student looking to meet people and practice some speaking.","age":18,"photo_url":"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTXoOrbcKIribhzRJP-qmiR9RCC-QsjZsZTwbpX3ikY-iFkChLs","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id": 6,"name":"Diego","email":"ddthiery@gmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Hola! Ofrezco conversación en español por un poco de inglés. Quedamos y echamos un rato tomando un cafe?","age":26,"photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Diego061115.jpg/150px-Diego061115.jpg","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id": 7,"name":"Manuel","email":"jvega@gmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Me encantan los videojuegos, la cerveza y el cine. Si quieres practicar un poco de español y ayudarme con el inglés, mándame un mensaje.","age":32,"photo_url":"http://upload.wikimedia.org/wikipedia/commons/4/44/Manuel_Seidl_-_SV_Mattersburg.jpg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id": 8,"name":"Jordan","email":"jordey@csu.state","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Studying Spanish for the first time this year and really need some help. We can meet at the park or for a coffee!","age":19,"photo_url":"https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAP6AAAAJGI3Mzk1OTY4LWVmM2UtNGZmZi1iY2ZiLTJjOGYyMjczODY4ZA.jpg","pair":true,"group":false,"online":false,"lang_preference":"en"}),
        knex('users').insert({"id": 9,"name":"Lola","email":"slopez8@cdbaby.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"Quiero practicar mi inglés. Pónte en contacto conmigo y hablamos!","age":40,"photo_url":"http://67.media.tumblr.com/7addb47f1155ecedc4ec32d0019ec4c6/tumblr_nlex4pP7Dl1sto1ndo1_1280.jpg","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id": 10,"name":"Antonio","email":"thicks9@theglobeandmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"Necesito aprobar el C1 de inglés en dos meses. Podemos estudiar juntos si también tienes que estudiar español","age":26,"photo_url":"http://www.stern.nyu.edu/faculty/static/photos/mgarcia.jpeg","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id": 11,"name":"Francois","email":"jkellya@dedecms.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"I'm in Sevilla for a study abroad course for 6 months and want to make some friends. Let me know if you want to practice your English doing something fun.","age":22,"photo_url":"https://pbs.twimg.com/profile_images/761965919438602240/ZX6Kp6kQ.jpg","pair":true,"group":false,"online":false,"lang_preference":"en"}),
        knex('users').insert({"id": 12,"name":"Ethan","email":"pfergusonb@cbsnews.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"I can meet on the weekends for a bite to eat or to have a beer somewhere in the city","age":25,"photo_url":"https://pbs.twimg.com/profile_images/580735790419832832/nGf7FX1C.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":13,"name":"Salma","email":"swarrenc@hexun.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Necesito practicar mi francés. Si quieres charlar un rato en español podemos quedar.","age":32,"photo_url":"https://pbs.twimg.com/profile_images/1155402916/Maria_Fanjul2.JPG","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":14,"name":"Angela","email":"hrobertsd@home.pl","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Voy a estudiar en París dos meses y necesito un tutor!","age":27,"photo_url":"http://www.hotel-r.net/im/hotel/es/angela.jpg","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id":15,"name":"Valerie","email":"jturnere@sitemeter.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Quiero sacar el C2 en español y quiero hablar mucho cuanto antes","age":35,"photo_url":"http://www.greymattermarketing.com/administration/media/images/ValerieBarro_2.jpg","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id":16,"name":"Sebastian","email":"jmooref@sciencedaily.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Soy profesor de español y quiero mejorar mi nivel de conversación.","age":40,"photo_url":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTMyMTk5OTY2Ml5BMl5BanBnXkFtZTcwNjA1Mzg5Mg@@._V1_UY317_CR131,0,214,317_AL_.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":17,"name":"María","email":"mariaf@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Hi guys, I'm looking for someone to study with twice a week at the library.","age":27,"photo_url":"https://pbs.twimg.com/profile_images/573600918144319488/Dz_wK2rW.jpeg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":18,"name":"Andrea","email":"andrea@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I need some help with my English. I am studying here for a year and would love to meet some great people.","age":25,"photo_url":"https://pbs.twimg.com/profile_images/489903129526145025/VJ53HqKh.jpeg","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":19,"name":"Santi","email":"santi@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I want to improve my English and exchange language practice. Email me if you're interested!","age":35,"photo_url":"https://pbs.twimg.com/profile_images/492744787066236928/TNjdfvdz_400x400.jpeg","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id":20,"name":"Chris","email":"chris@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"My friends and I have a language exchange group that meets on Tuesday nights. Message me if you want to join.","age":37,"photo_url":"https://pbs.twimg.com/profile_images/524902714220634112/mGfqyCX4.jpeg","pair":true,"group":true,"online":false,"lang_preference":"en"}),
        knex('users').insert({"id":21,"name":"Sam","email":"sam@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"2","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":25,"photo_url":"http://niptara.com/wp-content/uploads/2015/10/Samantha-Ruth-Prabhu-WikiBiography-Age-Height-Weight-Biodata-Family-ParentsBoyfriend.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":22,"name":"Ana","email":"ana@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"2","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":40,"photo_url":"https://sites.google.com/site/anaturpratsswebsite/_/rsrc/1468864089738/home/119_Anna%20Tur_ALTA.jpg?height=320&width=320","pair":false,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":23,"name":"Nathalie","email":"nat@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"2","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":18,"photo_url":"https://pbs.twimg.com/profile_images/583409784038133760/88ss70pf.jpg","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":24,"name":"Carlos","email":"carlos@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"2","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":29,"photo_url":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjMzMTcxMjI4N15BMl5BanBnXkFtZTgwMTM3NzYzNDE@._V1_UY317_CR27,0,214,317_AL_.jpg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":25,"name":"Laura","email":"laura@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"1","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":32,"photo_url":"https://pbs.twimg.com/profile_images/559075935865946113/kGW7McES.jpeg","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":26,"name":"Carlos","email":"carlos@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"1","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":40,"photo_url":"http://www.cims.nyu.edu/~borges/images/CB1.jpg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":27,"name":"Stephanie","email":"stephanie@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"1","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":22,"photo_url":"http://www.wri.org/sites/default/files/lorettacheung_2.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":28,"name":"Jimmy","email":"jimmy@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"1","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":29,"photo_url":"http://a.fastcompany.net/multisite_files/fastcompany/imagecache/inline-small/inline/2015/07/3048510-inline-h-1-jimmy-wales-wants-to-you-feel-good-about-paying-your-cell-phone-bill.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":29,"name":"Paloma","email":"paloma@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"5","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":34,"photo_url":"http://www.trbimg.com/img-53603d05/turbine/la-bio-paloma-esquivel","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":30,"name":"James","email":"james@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"5","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":22,"photo_url":"https://pbs.twimg.com/profile_images/632952422000779265/t7T-A7hl.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":31,"name":"Laila","email":"laila@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"5","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":45,"photo_url":"https://s3.amazonaws.com/rfums-bigtree/files/modules/alibiglou-laila-faculty-portrait.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":32,"name":"Marc","email":"marc@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"5","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":20,"photo_url":"https://pbs.twimg.com/profile_images/745907523555823616/0Tg6vXlo.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":33,"name":"Eli","email":"eli@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"4","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":20,"photo_url":"http://www.hotel-r.net/im/hotel/at/elisabeth-1.jpg","pair":true,"group":true,"online":false,"lang_preference":"en"}),
        knex('users').insert({"id":34,"name":"Luis","email":"luis@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"4","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":28,"photo_url":"https://pbs.twimg.com/profile_images/435808232221601792/-VzIB_HU.jpeg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":35,"name":"Teresa","email":"teresa@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"4","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":33,"photo_url":"https://upload.wikimedia.org/wikipedia/commons/2/2d/Teresa_Perales_wiki.JPG","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":36,"name":"Hans","email":"hans@email.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"4","description":"Bacon ipsum dolor amet rump kielbasa picanha pastrami pork. Sausage sirloin rump bresaola cupim, cow bacon flank porchetta pork chop picanha short loin kevin beef ribs salami. Flank bresaola salami kevin spare ribs fatback. Kevin porchetta spare ribs, shank kielbasa tenderloin rump shoulder short loin.","age":30,"photo_url":"http://www.atpworldtour.com/~/media/tennis/players/head-shot/2016/02/27/23/54/hans-podlipnik-headshot.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"})
        ]);
    });
};
