'use strict';

exports.seed = function(knex, Promise) {
  //deletes all existing entries
  return knex('users').del()
    .then(function() {
      return Promise.all([
        //inserts seed entries
        //begin seeds for user 1
        knex('users').insert({"id": 1,"name":"Jessica Austin","email":"jmoore0@tmall.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Hi, guys! I'm looking for an exchange partner to practice Spanish with twice a week.","age":23,"photo_url":"http://ww3.madonna.edu/crusaders/Images/story/WSOCC/austin_sign.jpg","pair":false,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id": 2,"name":"Bonnie Clyde","email":"bclyde@gmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I like speaking Spanish in my free time. Let's meet up for a coffee or beer.","age":62,"photo_url":"http://vignette1.wikia.nocookie.net/stargate/images/4/44/BB.jpg/revision/latest?cb=20150331174051","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id": 3,"name":"Lorena Schmidt","email":"ppeters2@mediafire.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I need to practice my English. I would love to meet in person or online!","age":25,"photo_url":"http://www.ggcalumni.net/image/four-pillar-society/2015-headshots/lorena/Lorena.jpg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id": 4,"name":"David Ortiz","email":"blopez3@youtu.be","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Need some basic conversational skills and can meet anytime on the weekends. Message me if you want to get in touch.","age":20,"photo_url":"https://pbs.twimg.com/profile_images/646374589916778496/i53D1Q35.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id": 5,"name":"Alexa Casas","email":"acasas@yahoo.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"I'm a foreign exchange student looking to meet people and practice some speaking.","age":18,"photo_url":"http://dummyimage.com/107x186.bmp/cc0000/ffffff","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id": 6,"name":"Diego Thiery","email":"ddthiery@gmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Hola! Ofrezco conversación en español por un poco de inglés. Quedamos y echamos un rato tomando un cafe?","age":26,"photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Diego061115.jpg/150px-Diego061115.jpg","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id": 7,"name":"Manuel Vega","email":"jvega@gmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Me encantan los videojuegos, la cerveza y el cine. Si quieres practicar un poco de español y ayudarme con el inglés, mándame un mensaje.","age":32,"photo_url":"http://upload.wikimedia.org/wikipedia/commons/4/44/Manuel_Seidl_-_SV_Mattersburg.jpg","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id": 8,"name":"Jordan Reynolds","email":"jordey@csu.state","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"7","description":"Studying Spanish for the first time this year and really need some help. We can meet at the park or for a coffee!","age":19,"photo_url":"https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAP6AAAAJGI3Mzk1OTY4LWVmM2UtNGZmZi1iY2ZiLTJjOGYyMjczODY4ZA.jpg","pair":true,"group":false,"online":false,"lang_preference":"en"}),
        knex('users').insert({"id": 9,"name":"Lola Rivera","email":"slopez8@cdbaby.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"Quiero practicar mi inglés. Pónte en contacto conmigo y hablamos!","age":40,"photo_url":"http://67.media.tumblr.com/7addb47f1155ecedc4ec32d0019ec4c6/tumblr_nlex4pP7Dl1sto1ndo1_1280.jpg","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id": 10,"name":"Antonio Petit","email":"thicks9@theglobeandmail.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"Necesito aprobar el C1 de inglés en dos meses. Podemos estudiar juntos si también tienes que estudiar español","age":26,"photo_url":"http://www.stern.nyu.edu/faculty/static/photos/mgarcia.jpeg","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id": 11,"name":"Francois Vogel","email":"jkellya@dedecms.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"I'm in Sevilla for a study abroad course for 6 months and want to make some friends. Let me know if you want to practice your English doing something fun.","age":22,"photo_url":"https://pbs.twimg.com/profile_images/761965919438602240/ZX6Kp6kQ.jpg","pair":true,"group":false,"online":false,"lang_preference":"en"}),
        knex('users').insert({"id": 12,"name":"Ethan Floyd","email":"pfergusonb@cbsnews.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"3","description":"I can meet on the weekends for a bite to eat or to have a beer somewhere in the city","age":25,"photo_url":"https://pbs.twimg.com/profile_images/580735790419832832/nGf7FX1C.jpg","pair":true,"group":false,"online":true,"lang_preference":"en"}),
        knex('users').insert({"id":13,"name":"Salma Medina","email":"swarrenc@hexun.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Necesito practicar mi francés. Si quieres charlar un rato en español podemos quedar.","age":32,"photo_url":"https://pbs.twimg.com/profile_images/1155402916/Maria_Fanjul2.JPG","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"id":14,"name":"Angela Vega","email":"hrobertsd@home.pl","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Voy a estudiar en París dos meses y necesito un tutor!","age":27,"photo_url":"http://www.hotel-r.net/im/hotel/es/angela.jpg","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id":15,"name":"Valerie Millet","email":"jturnere@sitemeter.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Quiero sacar el C2 en español y quiero hablar mucho cuanto antes","age":35,"photo_url":"http://www.greymattermarketing.com/administration/media/images/ValerieBarro_2.jpg","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        knex('users').insert({"id":16,"name":"Sebastian Castellanos","email":"jmooref@sciencedaily.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga","city_id":"6","description":"Soy profesor de español y quiero mejorar mi nivel de conversación.","age":40,"photo_url":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTMyMTk5OTY2Ml5BMl5BanBnXkFtZTcwNjA1Mzg5Mg@@._V1_UY317_CR131,0,214,317_AL_.jpg","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        // knex('users').insert({"id": ,"id":17,"name":"Samuel Hill","email":"shillg@i2i.jp","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""qXEZIVXP4Q","city_id":"2","description":"neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui","age":53,"photo_url":"http://dummyimage.com/122x139.png/ff4444/ffffff","pair":false,"group":true,"online":false,"lang_preference":"en"}),
        // knex('users').insert({"id": ,"id":18,"name":"Jason Castillo","email":"jcastilloh@gnu.org","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""H6JKKynyK","city_id":"2","description":"odio porttitor id consequat in consequat ut nulla sed accumsan felis ut","age":5,"photo_url":"http://dummyimage.com/149x151.png/ff4444/ffffff","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":19,"name":"Nancy Duncan","email":"nduncani@nhs.uk","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""RO5xP65P","city_id":"1","description":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis","age":30,"photo_url":"http://dummyimage.com/125x118.jpg/ff4444/ffffff","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":20,"name":"Richard Elliott","email":"relliottj@google.it","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""cqmYYvT","city_id":"1","description":"maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec","age":60,"photo_url":"http://dummyimage.com/101x122.jpg/5fa2dd/ffffff","pair":false,"group":true,"online":true,"lang_preference":"en"}),
        // knex('users').insert({"id": ,"id":21,"name":"Donna Schmidt","email":"dschmidtk@google.de","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""yPk9XqVGxNK","city_id":"1","description":"nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede","age":5,"photo_url":"http://dummyimage.com/184x128.png/5fa2dd/ffffff","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":22,"name":"Sharon Ellis","email":"sellisl@fda.gov","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""3SXczQ","city_id":"2","description":"quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar","age":33,"photo_url":"http://dummyimage.com/174x157.png/dddddd/000000","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":23,"name":"Mildred Harrison","email":"mharrisonm@github.io","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""hZknk3cw5As","city_id":"1","description":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui","age":41,"photo_url":"http://dummyimage.com/236x124.bmp/cc0000/ffffff","pair":false,"group":false,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":24,"name":"Denise Alexander","email":"dalexandern@ameblo.jp","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""UWADzoz2Gog","city_id":"1","description":"faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec","age":3,"photo_url":"http://dummyimage.com/192x110.bmp/dddddd/000000","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":25,"name":"Carol Reynolds","email":"creynoldso@hc360.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""b8It8jPBITAr","city_id":"2","description":"tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis","age":42,"photo_url":"http://dummyimage.com/227x155.bmp/cc0000/ffffff","pair":false,"group":true,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":26,"name":"Jane Cook","email":"jcookp@state.tx.us","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""OzLjyj","city_id":"2","description":"ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam","age":50,"photo_url":"http://dummyimage.com/116x196.png/ff4444/ffffff","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":27,"name":"Lori Ortiz","email":"lortizq@cbslocal.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""6XSXGdxKp4Ir","city_id":"1","description":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla","age":40,"photo_url":"http://dummyimage.com/110x191.bmp/5fa2dd/ffffff","pair":false,"group":true,"online":false,"lang_preference":"en"}),
        // knex('users').insert({"id": ,"id":28,"name":"Wanda Ramos","email":"wramosr@zdnet.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""iMqg4lOLMin","city_id":"1","description":"risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis","age":97,"photo_url":"http://dummyimage.com/170x219.jpg/ff4444/ffffff","pair":false,"group":false,"online":true,"lang_preference":"en"}),
        // knex('users').insert({"id": ,"id":29,"name":"Justin Turner","email":"jturners@4shared.com","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""YCqQGWi2","city_id":"2","description":"vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in","age":93,"photo_url":"http://dummyimage.com/188x239.png/cc0000/ffffff","pair":false,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id": ,"id":30,"name":"Irene Morgan","email":"imorgant@privacy.gov.au","pw":"$2a$10$JbRmIyFFTI3Dt0Ttxwcs6Og0Xpa2kiUxT9bY0vzfNRMwYBK.ilKga""ByMbjcy77Tk","city_id":"1","description":"fermentum donec ut mauris eget massa tempor convallis nulla neque libero","age":31,"photo_url":"http://dummyimage.com/210x210.jpg/dddddd/000000","pair":true,"group":true,"online":true,"lang_preference":"en"})
        ]);
    });
};
