'use strict';

exports.seed = function(knex, Promise) {
  //deletes all existing entries
  return knex('users').del()
    .then(function() {
      return Promise.all([
        //inserts seed entries
        //begin seeds for user 1
        knex('users').insert({"name":"Nicole Holmes","email":"nholmes0@marketwatch.com","pw":"qi62rj3y7BP","city":"Madrid","description":"condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu","age":67,"photo_url":"http://dummyimage.com/106x234.bmp/cc0000/ffffff","pair":false,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"name":"Benjamin Chapman","email":"bchapman1@cnn.com","pw":"uy3e4Oas","city":"Madrid","description":"nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis","age":46,"photo_url":"http://dummyimage.com/129x118.png/dddddd/000000","pair":false,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"name":"Paula Peters","email":"ppeters2@mediafire.com","pw":"8gRct4euLoww","city":"Madrid","description":"nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien","age":86,"photo_url":"http://dummyimage.com/129x126.jpg/5fa2dd/ffffff","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"name":"Brenda Lopez","email":"blopez3@youtu.be","pw":"CxBM5MCCpkry","city":"Madrid","description":"nisl venenatis lacinia aenean sit amet justo morbi ut odio cras","age":72,"photo_url":"http://dummyimage.com/194x231.png/ff4444/ffffff","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        knex('users').insert({"name":"Todd Lawrence","email":"tlawrence4@google.com.br","pw":"9hoMx8SEkXev","city":"Denver","description":"integer ac neque duis bibendum morbi non quam nec dui luctus rutrum","age":64,"photo_url":"http://dummyimage.com/107x186.bmp/cc0000/ffffff","pair":true,"group":false,"online":false,"lang_preference":"en"}),
        knex('users').insert({"name":"Joe Gutierrez","email":"jgutierrez5@webs.com","pw":"cslr6TSrD","city":"Denver","description":"vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo","age":94,"photo_url":"http://dummyimage.com/126x220.jpg/ff4444/ffffff","pair":false,"group":false,"online":false,"lang_preference":"es"}),
        knex('users').insert({"name":"Marie Murray","email":"mmurray6@squidoo.com","pw":"2v2vGGwIXOP","city":"Denver","description":"convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor","age":79,"photo_url":"http://dummyimage.com/207x161.bmp/ff4444/ffffff","pair":false,"group":false,"online":false,"lang_preference":"en"}),
        knex('users').insert({"name":"Jesse Watson","email":"jwatson7@gizmodo.com","pw":"XtRj4dXz8mTp","city":"Madrid","description":"sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id","age":88,"photo_url":"http://dummyimage.com/118x163.png/ff4444/ffffff","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        knex('users').insert({"name":"Samuel Lopez","email":"slopez8@cdbaby.com","pw":"Bf6ZliU4qu7b","city":"Denver","description":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc","age":88,"photo_url":"http://dummyimage.com/198x227.png/cc0000/ffffff","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        knex('users').insert({"name":"Timothy Hicks","email":"thicks9@theglobeandmail.com","pw":"jojcRvMstt74","city":"Madrid","description":"convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim","age":99,"photo_url":"http://dummyimage.com/205x105.jpg/5fa2dd/ffffff","pair":true,"group":true,"online":true,"lang_preference":"es"})
        // knex('users').insert({"id":11,"name":"Julie Kelly","email":"jkellya@dedecms.com","pw":"X6yJff4LG","city":"Denver","description":"sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla","age":97,"photo_url":"http://dummyimage.com/250x232.png/dddddd/000000","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":12,"name":"Patrick Ferguson","email":"pfergusonb@cbsnews.com","pw":"B25Mqzrf0","city":"Denver","description":"sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus","age":80,"photo_url":"http://dummyimage.com/169x129.png/ff4444/ffffff","pair":false,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":13,"name":"Shirley Warren","email":"swarrenc@hexun.com","pw":"RS7XgXlXD","city":"Madrid","description":"est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat","age":51,"photo_url":"http://dummyimage.com/178x169.png/5fa2dd/ffffff","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id":14,"name":"Harry Roberts","email":"hrobertsd@home.pl","pw":"KdwZ0E","city":"Denver","description":"pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam","age":80,"photo_url":"http://dummyimage.com/218x205.jpg/ff4444/ffffff","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":15,"name":"Joshua Turner","email":"jturnere@sitemeter.com","pw":"oxZkea8","city":"Madrid","description":"elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo","age":76,"photo_url":"http://dummyimage.com/243x112.bmp/cc0000/ffffff","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":16,"name":"Justin Moore","email":"jmooref@sciencedaily.com","pw":"n3bJ03","city":"Denver","description":"augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet","age":13,"photo_url":"http://dummyimage.com/127x227.jpg/ff4444/ffffff","pair":true,"group":true,"online":true,"lang_preference":"en"}),
        // knex('users').insert({"id":17,"name":"Samuel Hill","email":"shillg@i2i.jp","pw":"qXEZIVXP4Q","city":"Madrid","description":"neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui","age":53,"photo_url":"http://dummyimage.com/122x139.png/ff4444/ffffff","pair":false,"group":true,"online":false,"lang_preference":"en"}),
        // knex('users').insert({"id":18,"name":"Jason Castillo","email":"jcastilloh@gnu.org","pw":"H6JKKynyK","city":"Madrid","description":"odio porttitor id consequat in consequat ut nulla sed accumsan felis ut","age":5,"photo_url":"http://dummyimage.com/149x151.png/ff4444/ffffff","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":19,"name":"Nancy Duncan","email":"nduncani@nhs.uk","pw":"RO5xP65P","city":"Denver","description":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis","age":30,"photo_url":"http://dummyimage.com/125x118.jpg/ff4444/ffffff","pair":true,"group":false,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id":20,"name":"Richard Elliott","email":"relliottj@google.it","pw":"cqmYYvT","city":"Denver","description":"maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec","age":60,"photo_url":"http://dummyimage.com/101x122.jpg/5fa2dd/ffffff","pair":false,"group":true,"online":true,"lang_preference":"en"}),
        // knex('users').insert({"id":21,"name":"Donna Schmidt","email":"dschmidtk@google.de","pw":"yPk9XqVGxNK","city":"Denver","description":"nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede","age":5,"photo_url":"http://dummyimage.com/184x128.png/5fa2dd/ffffff","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":22,"name":"Sharon Ellis","email":"sellisl@fda.gov","pw":"3SXczQ","city":"Madrid","description":"quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar","age":33,"photo_url":"http://dummyimage.com/174x157.png/dddddd/000000","pair":true,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":23,"name":"Mildred Harrison","email":"mharrisonm@github.io","pw":"hZknk3cw5As","city":"Denver","description":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui","age":41,"photo_url":"http://dummyimage.com/236x124.bmp/cc0000/ffffff","pair":false,"group":false,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id":24,"name":"Denise Alexander","email":"dalexandern@ameblo.jp","pw":"UWADzoz2Gog","city":"Denver","description":"faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec","age":3,"photo_url":"http://dummyimage.com/192x110.bmp/dddddd/000000","pair":true,"group":false,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":25,"name":"Carol Reynolds","email":"creynoldso@hc360.com","pw":"b8It8jPBITAr","city":"Madrid","description":"tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis","age":42,"photo_url":"http://dummyimage.com/227x155.bmp/cc0000/ffffff","pair":false,"group":true,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id":26,"name":"Jane Cook","email":"jcookp@state.tx.us","pw":"OzLjyj","city":"Madrid","description":"ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam","age":50,"photo_url":"http://dummyimage.com/116x196.png/ff4444/ffffff","pair":true,"group":true,"online":true,"lang_preference":"es"}),
        // knex('users').insert({"id":27,"name":"Lori Ortiz","email":"lortizq@cbslocal.com","pw":"6XSXGdxKp4Ir","city":"Denver","description":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla","age":40,"photo_url":"http://dummyimage.com/110x191.bmp/5fa2dd/ffffff","pair":false,"group":true,"online":false,"lang_preference":"en"}),
        // knex('users').insert({"id":28,"name":"Wanda Ramos","email":"wramosr@zdnet.com","pw":"iMqg4lOLMin","city":"Denver","description":"risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis","age":97,"photo_url":"http://dummyimage.com/170x219.jpg/ff4444/ffffff","pair":false,"group":false,"online":true,"lang_preference":"en"}),
        // knex('users').insert({"id":29,"name":"Justin Turner","email":"jturners@4shared.com","pw":"YCqQGWi2","city":"Madrid","description":"vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in","age":93,"photo_url":"http://dummyimage.com/188x239.png/cc0000/ffffff","pair":false,"group":true,"online":false,"lang_preference":"es"}),
        // knex('users').insert({"id":30,"name":"Irene Morgan","email":"imorgant@privacy.gov.au","pw":"ByMbjcy77Tk","city":"Denver","description":"fermentum donec ut mauris eget massa tempor convallis nulla neque libero","age":31,"photo_url":"http://dummyimage.com/210x210.jpg/dddddd/000000","pair":true,"group":true,"online":true,"lang_preference":"en"})
        ]);
    });
};
